### ISSUE TITLE
GetUtcStartOfWeekInTimeZone issue

### ISSUE THREAD

**Issue by WEBSISCO** [microsoftgraph/msgraph-training-aspnet-core#14]
Hi, I found an issue on this function.
I'm in Italy - TimeZone UTC +1

`// Assumes Sunday as first day of week
int diff = System.DayOfWeek.Sunday - today.DayOfWeek;    > result: -2 (now is 27/10/2020 14:50 Tue)
var unspecifiedStart = DateTime.SpecifyKind(today.AddDays(diff), DateTimeKind.Unspecified);    > result 25/10/2020 00:00

// convert to UTC
return TimeZoneInfo.ConvertTimeToUtc(unspecifiedStart, timeZone);    >result 24/10/2020 22:00`

I have 2 problem:
1) First day of the week is Saturday
2) The Date Column and the Time column mismatching

![image](https://user-images.githubusercontent.com/5871258/97311877-236c5d80-1865-11eb-9df6-9a1d1b1579d8.png)

I copied the code from here
https://docs.microsoft.com/en-us/graph/tutorials/aspnet-core?tutorial-step=6

Thank you

**Comment by jasonjoh** [comment]
Thanks for reporting. For the first issue, that's a known limitation - I didn't do any logic to detect the proper start of week for the user - it's just hard coded to Sunday. It looks like you've already discovered that bit and have adjusted it.

That assumption of Sunday carries over into the view, which is causing the shift you're seeing. In [CalendarViewModel](https://github.com/microsoftgraph/msgraph-training-aspnet-core/blob/master/demo/GraphTutorial/Models/CalendarViewModel.cs), the events are sorted into buckets by the day of the week. I'm guessing that since you changed `_startOfweek` to Saturday, code like this is causing the shift:

https://github.com/microsoftgraph/msgraph-training-aspnet-core/blob/2930c681132dd71ae452d76a488eda83aef9f9db/demo/GraphTutorial/Models/CalendarViewModel.cs#L45-L53

It's the model for Saturday, but it's getting events for Sunday.

**Comment by WEBSISCO** [comment]
Hi,
I posted your code in CalendarController > GetUtcStartOfWeekInTimeZone, I didn't make any changes.
Sunday it's ok for me as first day of the week but that function return Saturday.

I fixed like this
CalendarController 
       
`        [AuthorizeForScopes(Scopes = new[] { "Calendars.Read" })]
        public async Task<IActionResult> Index()
        {
            try
            {
                var userTimeZone = TZConvert.GetTimeZoneInfo(
                    User.GetUserGraphTimeZone());
                var startOfWeek = CalendarController.GetUtcStartOfWeekInTimeZone(
                    **DateTime.Today**, userTimeZone);
`
I change it in DateTime.Now

and in GetUtcStartOfWeekInTimeZone I return the date 
`return TimeZoneInfo.ConvertTimeToUtc(unspecifiedStart, timeZone).**Date**;`
