### ISSUE TITLE
Sample crashes with `TimeZoneNotFoundException ` when run on macOS from AU

### ISSUE THREAD

**Issue by grumpydumpty** [microsoftgraph/msgraph-training-aspnet-core#3]
Timezone string returned by `User.GetUserGraphTimeZone()` (see [CalendarController.cs#L37](https://github.com/microsoftgraph/msgraph-training-aspnet-core/blob/master/demo/GraphTutorial/Controllers/CalendarController.cs#L37)) on macOS is "AUS Eastern Standard Time".

When this is passed to `TimeZoneInfo.FindSystemTimeZoneById()` (see [CalendarController.cs#L36](https://github.com/microsoftgraph/msgraph-training-aspnet-core/blob/master/demo/GraphTutorial/Controllers/CalendarController.cs#L36)) the sample is throwing a `TimeZoneNotFoundException`.

If I set a breakpoint and manually set the string returned by `User.GetUserGraphTimeZone()` to "Australia/Sydney" and continue, the sample runs without issue and the calendar page is filled out correctly.

Happy to raise issue on [dotnet/runtime](https://github.com/dotnet/runtime) or another repo, if you can point me to the right one.

![Screen Shot 2020-07-28 at 19 49 28](https://user-images.githubusercontent.com/9327690/88650196-d8c73200-d10b-11ea-89d0-d709053ac735.png)

**Comment by jasonjoh** [comment]
Interesting. The time zone name that comes from Graph is provided by Exchange Online, which gives Windows time zone names. Since you're on macOS, according to the [TimeZoneInfo docs](https://docs.microsoft.com/dotnet/api/system.timezoneinfo.findsystemtimezonebyid?view=netcore-3.1), TimeZoneInfo uses the IDs provided by the [ICU library](http://userguide.icu-project.org/datetime/timezone). This library seems to use the IANA time zone names.

So this seems to be by design with System.TimeZoneInfo, so it looks like your code will have to handle this. I'll have to take a closer look at this to come up with a solution, but this [Nuget package](https://www.nuget.org/packages/TimeZoneConverter/) looks promising.
